### ISSUE TITLE
Issue to trigger releases

### ISSUE THREAD

**Issue by OkonSamuel** [JuliaAI/FeatureSelection.jl#7]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by OkonSamuel** [comment]
@JuliaRegistrator register branch=master

**Comment by ablaom** [comment]
@JuliaRegistrator register branch=master

Release notes:

- Fix incorrect `is_wrapper` trait for `RecursiveFeatureElimination`. Now returns `true` (#15)
